export default {
  username: 'Username',
  password: 'Password',
  email: 'Email',
  login: 'Login',
  welcome: 'Welcome',
  register: 'Register',
  forgotYourPassword: 'Forgot your Password?',
  loginWithSocials: 'Or login with social account',
  registerWithSocials: 'Or sign up with social account',
  invalidEmail: 'Invalid email',
  textRequired: '{{ text }} is required',
  textCharacters: '{{ text }} must be at least {{ numbers }} characters',
  name: 'Name',
  send: 'Send',
  forgotPassword: 'Forgot password',
  signUp: 'Sign up',
  categories: 'Categories',
  home: 'Home',
  check: 'Check',
  fashionSale: 'Fashion sale',
  new: 'New',
  homeSubTitle: "You've never seen it before!",
  viewAll: 'View all',
  shop: 'Shop',
  haveAnAccount: 'Already have an Account?',
  filters: 'Filters',
  priceRange: 'Price range',
  colors: 'Colors',
  sizes: 'Sizes',
  category: 'Category',
  discard: 'Discard',
  apply: 'Apply',
  visualSearch: 'Visual Search',
  searchPhoto: 'Search by taking a photo',
  cropPhoto: 'Crop the item',
  findingResults: 'Finding similar results...',
  bag: 'Bag',
  favorites: 'Favorites',
  takePhoto: 'Take a photo',
  uploadImage: 'Upload an image',
  previewSearch: 'Preview and search',
  productDetails: 'Product details',
  noResults: 'No results yet',
  noResultsHelp: 'Run visual search to see the top image matches.',
  searchUnavailable: 'Visual search is unavailable right now',
  searchUnavailableHelp: 'Check your provider selection and environment variables.',
};
