export default {
    username: 'Username',
    password: 'Password',
    email: 'Email',
    login: 'Login',
    welcome: 'Welcome',
    register: 'Register',
    forgotYourPassword: 'Forgot your Password?',
    loginWithSocials: 'Or login with social account',
    registerWithSocials: 'Or sign up with social account',
    invalidEmail: 'Invalid email',
    textRequired: '{{ text }} is required',
    textCharacters: '{{ text }} must be at least {{ numbers }} characters',
    name: 'Name',
    send: 'Send',
    forgotPassword: 'Forgot password',
    signUp: 'Sign up',
   };